Vagrant.configure(2) do |config|
  config.vm.define "ubuntu1404" do |guest|
    guest.vm.box = "minimal/trusty64"
  end

  config.vm.define "debian8" do |guest|
    guest.vm.box = "minimal/jessie64"
  end

  config.vm.define "centos7" do |guest|
    guest.vm.box = "minimal/centos7"
  end
end
